### PR TITLE
sac_tutorial kernel added, support for function modification added

### PR DESCRIPTION
**Pull request by sbscholz**
the sac tutorial kernel pre-loads cells to get jupyter newbies an idea on what goes on
function modification is handy when developing functions step-wise. overloading is not possible within  a singly jupyter cell....

### CODE REVIEW

**Review by hv15 — APPROVED** [review]
looks good; should be mentioned that function modification only works with sac2c 1.3.3 rev 711 and newer.

**Comment by ashinkarov** [comment]
Fellas, I am not sure what are you doing here, but  setting `self.sac2c_so` to "XXX.dylib" looks dodgy, as it makes it OSX-specific.  You can use python to figure out the correct extension.

One should also solve the specification of sac2c path properly. Currently, the p variable is a really bad hack from the old days when I was experimenting with the setup.

**Comment by sbscholz** [comment]
By all means: please do help automating the setup…

Bodo

**Comment by hv15** [comment]
oops, missed the fixed path to XXX.dylib. Yes we should find the libsac2c and sac2c programmatically.

**Pull request merged**
